version=0.1
[default.global.parameters]
stack_name = "sedo-stack"

[default.deploy.parameters]
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ljzxqth2oo07"
s3_prefix = "sedo-stack"

