#!/bin/bash
rm -rf *.dist-info
rm -rf __pycache__
rm -f _*
rm -f *.so
rm -rf attr
rm -rf attrs
rm -rf awsgi
rm -rf bin
rm -rf boto3
rm -rf botocore
rm -rf certifi
rm -rf charset_normalizer
rm -rf click
rm -rf clickclick
rm -rf connexion
rm -rf dateutil
rm -rf flask
rm -rf flask_cors
rm -rf idna
rm -rf importlib_metadata
rm -rf importlib_resources
rm -rf inflection
rm -rf inflection.py
rm -rf itsdangerous
rm -rf jinja2
rm -rf jmespath
rm -rf jsonschema
rm -rf markupsafe
rm -rf packaging
rm -rf pyparsing
rm -rf pyrsistent
rm -rf requests
rm -rf s3transfer
rm -rf six.py
rm -rf urllib3
rm -rf werkzeug
rm -rf yaml
rm -rf zipp.py
